name: pull-request

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest

    concurrency:
      group: pull-request
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov

      - run: pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2