name: semantic-release

# this workflow only runs semantic-release, no testing, linting and such
# it should be triggered only by pull request merge
# for that master branch should be protected from direct push by branch protection rule

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    concurrency:
      group: semantic-release
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18.x

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}