name: semantic-release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    concurrency:
      group: release
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18.x

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - run: pytest
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}