name: semantic-release

# This workflow only runs semantic-release, no testing, linting and such.
# It should be triggered only by merging up-to-date development branch.
# To achieve that, master branch should have "Require a pull request before merging"
# and "Require branches to be up to date before merging" protection rules enabled.

on:
  push:
    branches:
      - master

concurrency:
  group: semantic-release
  cancel-in-progress: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18.x

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}